# -*- coding: utf-8 -*-
"""CNN complete

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_EEJP4-3Zpq7GjjggWOq9X3Y9eBXoL7
"""

!pip install roboflow opencv-python tensorflow keras scikit-learn matplotlib seaborn

import os
import numpy as np
import pandas as pd
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.applications import MobileNetV2, ResNet50, EfficientNetB0

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, precision_score, recall_score
from sklearn.utils.class_weight import compute_class_weight

np.random.seed(42)
tf.random.set_seed(42)

print("✅ Libraries imported successfully!")

# Dataset
# ============================================================

from roboflow import Roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="SzEImPE5FrQx88y4rrrz")
project = rf.workspace("skin-disease1").project("skrek-or-not")
version = project.version(1)
dataset = version.download("folder")
                # Download in multiclass format for CNN

print(f"✅ Dataset downloaded to: {dataset.location}")

train_df = pd.read_csv(f"{dataset.location}/train/_classes.csv")
valid_df = pd.read_csv(f"{dataset.location}/valid/_classes.csv")
test_df = pd.read_csv(f"{dataset.location}/test/_classes.csv")

print("\n📊 Dataset Distribution:")
print(f"Train - Healthy: {(train_df['Lesions']==0).sum()}, Lesions: {(train_df['Lesions']==1).sum()}")
print(f"Valid - Healthy: {(valid_df['Lesions']==0).sum()}, Lesions: {(valid_df['Lesions']==1).sum()}")
print(f"Test  - Healthy: {(test_df['Lesions']==0).sum()}, Lesions: {(test_df['Lesions']==1).sum()}")

def prepare_dataframe(df, split_name):
    """Add full image paths to dataframe"""
    df = df.copy()
    df['image_path'] = df['filename'].apply(
        lambda x: os.path.join(dataset.location, split_name, x)
    )
    df['label'] = df['Lesions'].astype(str)
    return df

train_df = prepare_dataframe(train_df, 'train')
valid_df = prepare_dataframe(valid_df, 'valid')
test_df = prepare_dataframe(test_df, 'test')

print("\n✅ Dataframes prepared with image paths")


IMG_SIZE = 224
BATCH_SIZE = 32

# Training data augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    zoom_range=0.2,
    shear_range=0.2,
    fill_mode='nearest'
)
valid_test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='image_path',
    y_col='label',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=True,
    seed=42
)

valid_generator = valid_test_datagen.flow_from_dataframe(
    dataframe=valid_df,
    x_col='image_path',
    y_col='label',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

test_generator = valid_test_datagen.flow_from_dataframe(
    dataframe=test_df,
    x_col='image_path',
    y_col='label',
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

print(f"\n✅ Data generators created")
print(f"   Training batches: {len(train_generator)}")
print(f"   Validation batches: {len(valid_generator)}")
print(f"   Test batches: {len(test_generator)}")

# Model
# ============================================================

def create_simple_cnn(input_shape=(224, 224, 3)):
    """Create a simple CNN from scratch"""
    model = models.Sequential([

        layers.Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        layers.Conv2D(64, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        layers.Conv2D(128, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        layers.Conv2D(256, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.25),

        layers.Flatten(),
        layers.Dense(512, activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(256, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(1, activation='sigmoid')
    ])

    return model

def create_transfer_learning_model(base_model_name='MobileNetV2', input_shape=(224, 224, 3)):
    """Create a model using transfer learning"""

# Not mine
    if base_model_name == 'MobileNetV2':
        base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=input_shape)
    elif base_model_name == 'ResNet50':
        base_model = ResNet50(weights='imagenet', include_top=False, input_shape=input_shape)
    elif base_model_name == 'EfficientNetB0':
        base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=input_shape)

    base_model.trainable = False

    # mine again
    model = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(256, activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(1, activation='sigmoid')
    ])

    return model

model = create_transfer_learning_model('MobileNetV2', input_shape=(IMG_SIZE, IMG_SIZE, 3))
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy', keras.metrics.Precision(), keras.metrics.Recall()]
)

print("✅ Model built and compiled!")
model.summary()

class_weights = compute_class_weight(
    'balanced',
    classes=np.unique(train_df['Lesions']),
    y=train_df['Lesions']
)
class_weight_dict = {0: class_weights[0], 1: class_weights[1]}

print(f"\n⚖️ Class weights: {class_weight_dict}")

# early stopping

callbacks = [
    EarlyStopping(
        monitor='val_loss',
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=5,
        min_lr=1e-7,
        verbose=1
    ),
    ModelCheckpoint(
        'best_fish_cnn_model.keras',
        monitor='val_loss',
        save_best_only=True,
        verbose=1
    )
]

#Training
# ============================================================

EPOCHS = 50

history = model.fit(
    train_generator,
    validation_data=valid_generator,
    epochs=EPOCHS,
    callbacks=callbacks,
    class_weight=class_weight_dict,
    verbose=1
)


# Graphs
# ============================================================

def plot_training_history(history):
    """Plot training and validation metrics"""
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))

    # Accuracy
    axes[0, 0].plot(history.history['accuracy'], label='Train Accuracy')
    axes[0, 0].plot(history.history['val_accuracy'], label='Val Accuracy')
    axes[0, 0].set_title('Model Accuracy')
    axes[0, 0].set_xlabel('Epoch')
    axes[0, 0].set_ylabel('Accuracy')
    axes[0, 0].legend()
    axes[0, 0].grid(True)

    # Loss
    axes[0, 1].plot(history.history['loss'], label='Train Loss')
    axes[0, 1].plot(history.history['val_loss'], label='Val Loss')
    axes[0, 1].set_title('Model Loss')
    axes[0, 1].set_xlabel('Epoch')
    axes[0, 1].set_ylabel('Loss')
    axes[0, 1].legend()
    axes[0, 1].grid(True)

    # Precision
    axes[1, 0].plot(history.history['precision'], label='Train Precision')
    axes[1, 0].plot(history.history['val_precision'], label='Val Precision')
    axes[1, 0].set_title('Model Precision')
    axes[1, 0].set_xlabel('Epoch')
    axes[1, 0].set_ylabel('Precision')
    axes[1, 0].legend()
    axes[1, 0].grid(True)

    # Recall
    axes[1, 1].plot(history.history['recall'], label='Train Recall')
    axes[1, 1].plot(history.history['val_recall'], label='Val Recall')
    axes[1, 1].set_title('Model Recall')
    axes[1, 1].set_xlabel('Epoch')
    axes[1, 1].set_ylabel('Recall')
    axes[1, 1].legend()
    axes[1, 1].grid(True)

    plt.tight_layout()
    plt.show()

plot_training_history(history)



test_generator.reset()
y_pred_probs = model.predict(test_generator, verbose=1)
y_pred = (y_pred_probs > 0.5).astype(int).flatten()
y_true = test_generator.classes

def calculate_f_star(f1):
    """Calculate F* score from F1 score using formula: F* = F / (2 - F)"""
    return f1 / (2 - f1) if f1 > 0 else 0

accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, zero_division=0)
recall = recall_score(y_true, y_pred, zero_division=0)
f1 = f1_score(y_true, y_pred, zero_division=0)
f_star = calculate_f_star(f1)

print("\n" + "="*60)
print("TEST SET PERFORMANCE METRICS")
print("="*60)
print(f"  Accuracy:  {accuracy:.4f}")
print(f"  Precision: {precision:.4f}")
print(f"  Recall:    {recall:.4f}")
print(f"  F1 Score:  {f1:.4f}")
print(f"  F* Score:  {f_star:.4f}")
print("="*60)


print("\nDetailed Classification Report:")
print(classification_report(y_true, y_pred, target_names=['Healthy (0)', 'Lesions (1)']))

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Healthy', 'Lesions'],
            yticklabels=['Healthy', 'Lesions'])
plt.title('Confusion Matrix - Test Set')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

valid_generator.reset()
y_val_pred_probs = model.predict(valid_generator, verbose=0)
y_val_pred = (y_val_pred_probs > 0.5).astype(int).flatten()
y_val_true = valid_generator.classes

val_accuracy = accuracy_score(y_val_true, y_val_pred)
val_precision = precision_score(y_val_true, y_val_pred, zero_division=0)
val_recall = recall_score(y_val_true, y_val_pred, zero_division=0)
val_f1 = f1_score(y_val_true, y_val_pred, zero_division=0)
val_f_star = calculate_f_star(val_f1)

# Create comparison dataframe
comparison_df = pd.DataFrame({
    'Dataset': ['Validation', 'Test'],
    'Accuracy': [val_accuracy, accuracy],
    'Precision': [val_precision, precision],
    'Recall': [val_recall, recall],
    'F1 Score': [val_f1, f1],
    'F* Score': [val_f_star, f_star]
})

print("\n" + "="*60)
print("VALIDATION vs TEST COMPARISON")
print("="*60)
print(comparison_df.to_string(index=False))
print("="*60)

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'F* Score']

for idx, metric in enumerate(metrics):
    row = idx // 3
    col = idx % 3
    ax = axes[row, col]

    bars = ax.bar(comparison_df['Dataset'], comparison_df[metric],
                   color=['skyblue', 'lightcoral'])
    ax.set_ylabel(metric, fontsize=12)
    ax.set_title(f'{metric} Comparison', fontsize=14, fontweight='bold')
    ax.set_ylim([0, 1.1])
    ax.grid(axis='y', alpha=0.3)

    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.02,
                f'{height:.3f}', ha='center', va='bottom', fontsize=10)

axes[1, 2].axis('off')

plt.tight_layout()
plt.show()


model.save('fish_lesion_cnn_model.keras')  # Keras format
model.save('fish_lesion_cnn_model.h5')      # H5 format

print(" Model saved!")
print("   - fish_lesion_cnn_model.keras")
print("   - fish_lesion_cnn_model.h5")
print("   - best_fish_cnn_model.keras (best checkpoint)")


def predict_fish_health(image_path, model, img_size=224):
    """
    Predict if a fish has lesions from an image

    Args:
        image_path: Path to the fish image
        model: Trained Keras model
        img_size: Image size for model input

    Returns:
        Dictionary with prediction results
    """
    img = cv2.imread(image_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (img_size, img_size))
    img = img / 255.0  # Normalize
    img = np.expand_dims(img, axis=0)  # Add batch dimension

    pred_prob = model.predict(img, verbose=0)[0][0]
    pred_class = 1 if pred_prob > 0.5 else 0

    result = {
        'prediction': 'LESIONS DETECTED' if pred_class == 1 else 'HEALTHY',
        'confidence': float(pred_prob if pred_class == 1 else 1 - pred_prob),
        'lesion_probability': float(pred_prob),
        'healthy_probability': float(1 - pred_prob)
    }

    return result

sample_image = test_df.iloc[0]['image_path']
result = predict_fish_health(sample_image, model, IMG_SIZE)
print(f"\nSample prediction:")
print(f"  Image: {os.path.basename(sample_image)}")
print(f"  Prediction: {result['prediction']}")
print(f"  Confidence: {result['confidence']:.2%}")

# Learning curve
# ============================================================

print("\n" + "="*60)
print("CNN LEARNING CURVE - COMPARING DATA SIZES")
print("="*60)

data_percentages = [0.5, 0.75, 1.0]
cnn_learning_results = []

full_train_df_cnn = pd.concat([train_df, valid_df], ignore_index=True)

def prepare_df_for_cnn(df, split_name):
    df = df.copy()
    df['image_path'] = df['filename'].apply(
        lambda x: os.path.join(dataset.location, split_name, x)
    )
    df['label'] = df['Lesions'].astype(str)
    return df

full_train_df_cnn = pd.concat([
    prepare_df_for_cnn(train_df, 'train'),
    prepare_df_for_cnn(valid_df, 'valid')
], ignore_index=True)

test_df_cnn = prepare_df_for_cnn(test_df, 'test')

for pct in data_percentages:
    print(f"\n{'='*60}")
    print(f"Training CNN with {int(pct*100)}% of data")
    print(f"{'='*60}")

    n_samples = int(len(full_train_df_cnn) * pct)

    if pct < 1.0:
        train_subset = full_train_df_cnn.sample(n=n_samples, random_state=42)
    else:
        train_subset = full_train_df_cnn

    print(f"Training samples: {n_samples}")
    print(f"Class distribution: Healthy={np.sum(train_subset['Lesions']==0)}, Lesions={np.sum(train_subset['Lesions']==1)}")

    IMG_SIZE = 224
    BATCH_SIZE = 32

    train_datagen = ImageDataGenerator(
        rescale=1./255,
        validation_split=0.2,
        rotation_range=20,
        width_shift_range=0.2,
        height_shift_range=0.2,
        horizontal_flip=True,
        zoom_range=0.2
    )

    test_datagen = ImageDataGenerator(rescale=1./255)

    train_generator = train_datagen.flow_from_dataframe(
        dataframe=train_subset,
        x_col='image_path',
        y_col='label',
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='binary',
        subset='training',
        shuffle=True,
        seed=42
    )

    valid_generator = train_datagen.flow_from_dataframe(
        dataframe=train_subset,
        x_col='image_path',
        y_col='label',
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='binary',
        subset='validation',
        shuffle=False
    )

    test_generator = test_datagen.flow_from_dataframe(
        dataframe=test_df_cnn,
        x_col='image_path',
        y_col='label',
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='binary',
        shuffle=False
    )

    base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(IMG_SIZE, IMG_SIZE, 3))
    base_model.trainable = False

    model_subset = models.Sequential([
        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(256, activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.5),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(1, activation='sigmoid')
    ])

    model_subset.compile(
        optimizer=keras.optimizers.Adam(learning_rate=0.001),
        loss='binary_crossentropy',
        metrics=['accuracy', keras.metrics.Precision(), keras.metrics.Recall()]
    )

    class_weights = compute_class_weight(
        'balanced',
        classes=np.unique(train_subset['Lesions']),
        y=train_subset['Lesions']
    )
    class_weight_dict = {0: class_weights[0], 1: class_weights[1]}

    print(f"\nTraining CNN for {int(pct*100)}% data...")
    history_subset = model_subset.fit(
        train_generator,
        validation_data=valid_generator,
        epochs=30,
        callbacks=[
            EarlyStopping(monitor='val_loss', patience=7, restore_best_weights=True, verbose=0),
            ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=0)
        ],
        class_weight=class_weight_dict,
        verbose=1
    )

    print("\nEvaluating on test set...")
    test_generator.reset()
    y_pred_probs = model_subset.predict(test_generator, verbose=0)
    y_pred = (y_pred_probs > 0.5).astype(int).flatten()
    y_true = test_generator.classes

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, zero_division=0)
    recall = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    f_star = calculate_f_star(f1)

    cnn_learning_results.append({
        'data_percentage': int(pct * 100),
        'training_samples': n_samples,
        'epochs_trained': len(history_subset.history['loss']),
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'f_star': f_star
    })

    print(f"\nResults:")
    print(f"  Epochs trained: {len(history_subset.history['loss'])}")
    print(f"  Accuracy:  {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1 Score:  {f1:.4f}")
    print(f"  F* Score:  {f_star:.4f}")

    keras.backend.clear_session()

cnn_learning_df = pd.DataFrame(cnn_learning_results)

# Learning Curve
# ============================================================

print("\n" + "="*60)
print("PLOTTING CNN LEARNING CURVE")
print("="*60)

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('CNN Learning Curve: Performance vs Training Data Size',
             fontsize=16, fontweight='bold', y=1.02)

metrics = ['accuracy', 'precision', 'recall', 'f1', 'f_star']
titles = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'F* Score']
colors = ['#3498db', '#e74c3c', '#2ecc71', '#f39c12', '#9b59b6']

for idx, (metric, title, color) in enumerate(zip(metrics, titles, colors)):
    row = idx // 3
    col = idx % 3
    ax = axes[row, col]

    ax.plot(cnn_learning_df['data_percentage'],
            cnn_learning_df[metric],
            's-',
            color=color,
            linewidth=3,
            markersize=12,
            label=title)

    for i, row_data in cnn_learning_df.iterrows():
        ax.text(row_data['data_percentage'],
                row_data[metric] + 0.02,
                f"{row_data[metric]:.3f}",
                ha='center',
                va='bottom',
                fontsize=10,
                fontweight='bold')

    ax.set_xlabel('Training Data Size (%)', fontsize=12, fontweight='bold')
    ax.set_ylabel(title, fontsize=12, fontweight='bold')
    ax.set_title(f'{title} vs Data Size', fontsize=13, fontweight='bold')
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.set_ylim([0, 1.1])
    ax.set_xticks(cnn_learning_df['data_percentage'])

ax = axes[1, 2]
ax.axis('off')

summary_text = "Summary Table\n" + "="*50 + "\n\n"
summary_text += f"{'Data %':<10} {'Samples':<10} {'Epochs':<8} {'Acc':<8} {'F1':<8}\n"
summary_text += "-"*50 + "\n"
for _, row in cnn_learning_df.iterrows():
    summary_text += f"{row['data_percentage']:<10} {row['training_samples']:<10} {row['epochs_trained']:<8} {row['accuracy']:<8.3f} {row['f1']:<8.3f}\n"

acc_50_to_75 = ((cnn_learning_df.iloc[1]['accuracy'] - cnn_learning_df.iloc[0]['accuracy']) /
                cnn_learning_df.iloc[0]['accuracy'] * 100)
acc_75_to_100 = ((cnn_learning_df.iloc[2]['accuracy'] - cnn_learning_df.iloc[1]['accuracy']) /
                 cnn_learning_df.iloc[1]['accuracy'] * 100)

summary_text += "\n" + "="*50 + "\n"
summary_text += "Improvement Rates:\n"
summary_text += f"50% → 75%:  {acc_50_to_75:+.1f}%\n"
summary_text += f"75% → 100%: {acc_75_to_100:+.1f}%\n"

ax.text(0.1, 0.5, summary_text,
        fontsize=10,
        family='monospace',
        verticalalignment='center')

plt.tight_layout()
plt.savefig('cnn_learning_curve.png', dpi=300, bbox_inches='tight')
plt.show()


print("\n" + "="*60)
print("CNN PERFORMANCE COMPARISON")
print("="*60)
print(cnn_learning_df.to_string(index=False))
print("="*60)