# -*- coding: utf-8 -*-
"""SVM complete

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPZleg3otaWjZMVeyBlKrECstVkJYMDg
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import cv2

sns.set_style('whitegrid')

# DATA
# ============================================================================
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="SzEImPE5FrQx88y4rrrz")
project = rf.workspace("skin-disease1").project("fishies-7rkfo")
version = project.version(1)
dataset = version.download("multiclass")

train_df = pd.read_csv(f"{dataset.location}/train/_classes.csv")
valid_df = pd.read_csv(f"{dataset.location}/valid/_classes.csv")
test_df = pd.read_csv(f"{dataset.location}/test/_classes.csv")

print("Dataset distribution:")
print(f"Train: {train_df['Lesions'].value_counts().to_dict()}")
print(f"Valid: {valid_df['Lesions'].value_counts().to_dict()}")
print(f"Test: {test_df['Lesions'].value_counts().to_dict()}")

# load images and labels
def load_images_and_labels(df, split_folder, img_size=(64, 64)):
    images = []
    labels = []

    for idx, row in df.iterrows():
        img_path = os.path.join(dataset.location, split_folder, row['filename'])


        img = cv2.imread(img_path)
        if img is not None:
            img = cv2.resize(img, img_size)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # Convert to RGB
            images.append(img.flatten())  # Flatten for SVM
            labels.append(row['Lesions'])

    return np.array(images), np.array(labels)

# training data
print("\nLoading training images...")
X_train, y_train = load_images_and_labels(train_df, 'train')
print(f"Training set: {X_train.shape}, Labels: {y_train.shape}")

# validation data
print("Loading validation images...")
X_valid, y_valid = load_images_and_labels(valid_df, 'valid')
print(f"Validation set: {X_valid.shape}, Labels: {y_valid.shape}")

# test data
print("Loading test images...")
X_test, y_test = load_images_and_labels(test_df, 'test')
print(f"Test set: {X_test.shape}, Labels: {y_test.shape}")

X_train_full = np.vstack([X_train, X_valid])
y_train_full = np.concatenate([y_train, y_valid])

print(f"\nFull training set: {X_train_full.shape}")
print(f"Test set: {X_test.shape}")
print(f"Number of classes: {len(np.unique(y_train_full))}")


# scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_full)
X_test_scaled = scaler.transform(X_test)

print("\nData has been scaled using StandardScaler")

# Traingin
# ============================================================================

kernels = ['linear', 'rbf', 'poly']
results = {}

for kernel in kernels:
    print(f"\n{'='*60}")
    print(f"Training SVM with {kernel.upper()} kernel")
    print('='*60)

    svm_model = SVC(kernel=kernel, random_state=42)
    svm_model.fit(X_train_scaled, y_train_full)

    y_pred = svm_model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    results[kernel] = accuracy

    print(f"\nAccuracy: {accuracy:.4f}")

    # graphs
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=['Healthy (0)', 'Lesions (1)']))

    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Healthy', 'Lesions'],
                yticklabels=['Healthy', 'Lesions'])
    plt.title(f'Confusion Matrix - {kernel.upper()} Kernel')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

print("\n" + "="*60)
print("KERNEL COMPARISON")
print("="*60)
for kernel, acc in results.items():
    print(f"{kernel.upper()}: {acc:.4f}")

# TUNING
# ============================================================================

print("\n" + "="*60)
print("HYPERPARAMETER TUNING")
print("="*60)

param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1],
    'kernel': ['rbf', 'poly', 'linear']
}

grid_search = GridSearchCV(
    SVC(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    verbose=1,
    n_jobs=-1
)

print("\nPerforming Grid Search (this may take a moment)...")
grid_search.fit(X_train_scaled, y_train_full)

print("\nBest Parameters:")
print(grid_search.best_params_)
print(f"\nBest Cross-Validation Score: {grid_search.best_score_:.4f}")

best_model = grid_search.best_estimator_
y_pred_best = best_model.predict(X_test_scaled)
accuracy_best = accuracy_score(y_test, y_pred_best)

print(f"\nTest Set Accuracy with Best Model: {accuracy_best:.4f}")

print("\nClassification Report (Best Model):")
print(classification_report(y_test, y_pred_best, target_names=['Healthy (0)', 'Lesions (1)']))

cm_best = confusion_matrix(y_test, y_pred_best)
plt.figure(figsize=(8, 6))
sns.heatmap(cm_best, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Healthy', 'Lesions'],
            yticklabels=['Healthy', 'Lesions'])
plt.title('Confusion Matrix - Best Model')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.show()

from sklearn.metrics import f1_score, precision_score, recall_score

print("\n" + "="*60)
print("DETAILED PERFORMANCE METRICS")
print("="*60)

def calculate_f_star(f1):
    """Calculate F* score from F1 score using formula: F* = F / (2 - F)"""
    return f1 / (2 - f1)

print("\nMetrics for each kernel:")
print("-" * 60)

kernel_metrics = []

for kernel in kernels:

    svm_model = SVC(kernel=kernel, random_state=42)
    svm_model.fit(X_train_scaled, y_train_full)
    y_pred = svm_model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    f_star = calculate_f_star(f1)

    kernel_metrics.append({
        'kernel': kernel,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'f_star': f_star
    })

    print(f"\n{kernel.upper()} Kernel:")
    print(f"  Accuracy:  {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1 Score:  {f1:.4f}")
    print(f"  F* Score:  {f_star:.4f}")

print("\n" + "="*60)
print("BEST MODEL METRICS (from GridSearch)")
print("="*60)

y_pred_best = best_model.predict(X_test_scaled)

accuracy_best = accuracy_score(y_test, y_pred_best)
precision_best = precision_score(y_test, y_pred_best, average='weighted')
recall_best = recall_score(y_test, y_pred_best, average='weighted')
f1_best = f1_score(y_test, y_pred_best, average='weighted')
f_star_best = calculate_f_star(f1_best)

print(f"\nBest Model ({best_model.kernel} kernel, C={best_model.C}, gamma={best_model.gamma}):")
print(f"  Accuracy:  {accuracy_best:.4f}")
print(f"  Precision: {precision_best:.4f}")
print(f"  Recall:    {recall_best:.4f}")
print(f"  F1 Score:  {f1_best:.4f}")
print(f"  F* Score:  {f_star_best:.4f}")




print("\nPer-class metrics (Best Model):")
print("-" * 60)

precision_per_class = precision_score(y_test, y_pred_best, average=None)
recall_per_class = recall_score(y_test, y_pred_best, average=None)
f1_per_class = f1_score(y_test, y_pred_best, average=None)
f_star_per_class = [calculate_f_star(f) for f in f1_per_class]

class_names = ['Healthy (0)', 'Lesions (1)']
for i, class_name in enumerate(class_names):
    print(f"\n{class_name}:")
    print(f"  Precision: {precision_per_class[i]:.4f}")
    print(f"  Recall:    {recall_per_class[i]:.4f}")
    print(f"  F1 Score:  {f1_per_class[i]:.4f}")
    print(f"  F* Score:  {f_star_per_class[i]:.4f}")

metrics_summary = pd.DataFrame({
    'Kernel': [m['kernel'] for m in kernel_metrics] + ['Best Model'],
    'Accuracy': [m['accuracy'] for m in kernel_metrics] + [accuracy_best],
    'Precision': [m['precision'] for m in kernel_metrics] + [precision_best],
    'Recall': [m['recall'] for m in kernel_metrics] + [recall_best],
    'F1 Score': [m['f1'] for m in kernel_metrics] + [f1_best],
    'F* Score': [m['f_star'] for m in kernel_metrics] + [f_star_best]
})

# More Graphs
print("\n" + "="*60)
print("SUMMARY TABLE")
print("="*60)
print(metrics_summary.to_string(index=False))


fig, axes = plt.subplots(2, 3, figsize=(18, 10))

metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'F* Score']
for idx, metric in enumerate(metrics):
    ax = axes[idx // 3, idx % 3]
    ax.bar(metrics_summary['Kernel'], metrics_summary[metric], color='skyblue', edgecolor='navy')
    ax.set_ylabel(metric)
    ax.set_title(f'{metric} Comparison')
    ax.set_ylim([0, 1.1])
    ax.grid(axis='y', alpha=0.3)
    ax.tick_params(axis='x', rotation=45)

    for i, v in enumerate(metrics_summary[metric]):
        ax.text(i, v + 0.02, f'{v:.3f}', ha='center', va='bottom', fontsize=9)

axes[1, 2].axis('off')

plt.tight_layout()
plt.show()

# Learnign curve
# ============================================================

print("\n" + "="*60)
print("SVM LEARNING CURVE - COMPARING DATA SIZES")
print("="*60)


from sklearn.utils import resample

data_percentages = [0.5, 0.75, 1.0]
svm_learning_results = []

X_full = X_train_full
y_full = y_train_full

for pct in data_percentages:
    print(f"\n{'='*60}")
    print(f"Training SVM with {int(pct*100)}% of data")
    print(f"{'='*60}")

    n_samples = int(len(X_full) * pct)

    if pct < 1.0:
        X_sampled, y_sampled = resample(X_full, y_full,
                                         n_samples=n_samples,
                                         random_state=42,
                                         stratify=y_full)
    else:
        X_sampled = X_full
        y_sampled = y_full

    print(f"Training samples: {n_samples}")
    print(f"Class distribution: Healthy={np.sum(y_sampled==0)}, Lesions={np.sum(y_sampled==1)}")

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_sampled)
    X_test_scaled = scaler.transform(X_test)

    print("\nTraining SVM...")
    svm_model = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
    svm_model.fit(X_train_scaled, y_sampled)

    y_pred = svm_model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    f_star = calculate_f_star(f1)

    svm_learning_results.append({
        'data_percentage': int(pct * 100),
        'training_samples': n_samples,
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'f_star': f_star
    })

    print(f"\nResults:")
    print(f"  Accuracy:  {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1 Score:  {f1:.4f}")
    print(f"  F* Score:  {f_star:.4f}")

svm_learning_df = pd.DataFrame(svm_learning_results)

# EVEN MORE GRAPHS AM I EVEN GONNA USE THESE

print("\n" + "="*60)
print("PLOTTING SVM LEARNING CURVE")
print("="*60)

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('SVM Learning Curve: Performance vs Training Data Size',
             fontsize=16, fontweight='bold', y=1.02)

metrics = ['accuracy', 'precision', 'recall', 'f1', 'f_star']
titles = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'F* Score']
colors = ['#3498db', '#e74c3c', '#2ecc71', '#f39c12', '#9b59b6']

for idx, (metric, title, color) in enumerate(zip(metrics, titles, colors)):
    row = idx // 3
    col = idx % 3
    ax = axes[row, col]

    ax.plot(svm_learning_df['data_percentage'],
            svm_learning_df[metric],
            'o-',
            color=color,
            linewidth=3,
            markersize=12,
            label=title)

    for i, row_data in svm_learning_df.iterrows():
        ax.text(row_data['data_percentage'],
                row_data[metric] + 0.02,
                f"{row_data[metric]:.3f}",
                ha='center',
                va='bottom',
                fontsize=10,
                fontweight='bold')

    ax.set_xlabel('Training Data Size (%)', fontsize=12, fontweight='bold')
    ax.set_ylabel(title, fontsize=12, fontweight='bold')
    ax.set_title(f'{title} vs Data Size', fontsize=13, fontweight='bold')
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.set_ylim([0, 1.1])
    ax.set_xticks(svm_learning_df['data_percentage'])

ax = axes[1, 2]
ax.axis('off')

summary_text = "Summary Table\n" + "="*40 + "\n\n"
summary_text += f"{'Data %':<10} {'Samples':<10} {'Acc':<8} {'F1':<8} {'F*':<8}\n"
summary_text += "-"*40 + "\n"
for _, row in svm_learning_df.iterrows():
    summary_text += f"{row['data_percentage']:<10} {row['training_samples']:<10} {row['accuracy']:<8.3f} {row['f1']:<8.3f} {row['f_star']:<8.3f}\n"

acc_50_to_75 = ((svm_learning_df.iloc[1]['accuracy'] - svm_learning_df.iloc[0]['accuracy']) /
                svm_learning_df.iloc[0]['accuracy'] * 100)
acc_75_to_100 = ((svm_learning_df.iloc[2]['accuracy'] - svm_learning_df.iloc[1]['accuracy']) /
                 svm_learning_df.iloc[1]['accuracy'] * 100)

summary_text += "\n" + "="*40 + "\n"
summary_text += "Improvement Rates:\n"
summary_text += f"50% → 75%:  {acc_50_to_75:+.1f}%\n"
summary_text += f"75% → 100%: {acc_75_to_100:+.1f}%\n"

ax.text(0.1, 0.5, summary_text,
        fontsize=11,
        family='monospace',
        verticalalignment='center')

plt.tight_layout()
plt.savefig('svm_learning_curve.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n✅ SVM Learning Curve Complete!")
print(f"📁 Graph saved as: svm_learning_curve.png")
print("\n" + "="*60)
print("SVM PERFORMANCE COMPARISON")
print("="*60)
print(svm_learning_df.to_string(index=False))
print("="*60)