# -*- coding: utf-8 -*-
"""YOLO complete

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJljsR_mgCVVObImyZkZvj2KaZ6JHFDe
"""

!pip install ultralytics roboflow supervision -q

import numpy as np
from ultralytics import YOLO
import os
import shutil
from pathlib import Path
import yaml
import cv2
from IPython.display import Image, display
from google.colab import files
import zipfile
import numpy as np  # Import numpy
import pandas as pd # Import pandas for DataFrame
import matplotlib.pyplot as plt # Import matplotlib for plotting

#directory
BASE_DIR = '/content/fish_lesion_detection'
DATASET_DIR = f'{BASE_DIR}/dataset'
IMAGES_DIR = f'{DATASET_DIR}/images'
LABELS_DIR = f'{DATASET_DIR}/labels'

for split in ['train', 'val', 'test']:
    os.makedirs(f'{IMAGES_DIR}/{split}', exist_ok=True)
    os.makedirs(f'{LABELS_DIR}/{split}', exist_ok=True)

print("✅ Directory structure created!")

# dataset
# ============================================================
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="SzEImPE5FrQx88y4rrrz")
project = rf.workspace("skin-disease1").project("fishies-7rkfo")
version = project.version(1)
dataset = version.download("yolov8")

downloaded_dataset_path = dataset.location

print(f"\n📁 Moving dataset from {downloaded_dataset_path} to {BASE_DIR}/dataset...")

# Clear existing empty directories to prevent CopyTree errors if they exist but are empty
for split_name in ['train', 'val', 'test']:
    shutil.rmtree(f'{IMAGES_DIR}/{split_name}', ignore_errors=True)
    shutil.rmtree(f'{LABELS_DIR}/{split_name}', ignore_errors=True)
    os.makedirs(f'{IMAGES_DIR}/{split_name}', exist_ok=True)
    os.makedirs(f'{LABELS_DIR}/{split_name}', exist_ok=True)

# Copy train split
shutil.copytree(f'{downloaded_dataset_path}/train/images', f'{IMAGES_DIR}/train', dirs_exist_ok=True)
shutil.copytree(f'{downloaded_dataset_path}/train/labels', f'{LABELS_DIR}/train', dirs_exist_ok=True)

# Copy valid split (rename to val)
shutil.copytree(f'{downloaded_dataset_path}/valid/images', f'{IMAGES_DIR}/val', dirs_exist_ok=True)
shutil.copytree(f'{downloaded_dataset_path}/valid/labels', f'{LABELS_DIR}/val', dirs_exist_ok=True)


# Copy test split
shutil.copytree(f'{downloaded_dataset_path}/test/images', f'{IMAGES_DIR}/test', dirs_exist_ok=True)
shutil.copytree(f'{downloaded_dataset_path}/test/labels', f'{LABELS_DIR}/test', dirs_exist_ok=True)

print("✅ Dataset moved successfully!")

# ============================================================
# STEP 4: Create Dataset Configuration File
# ============================================================

dataset_config = {
    'path': DATASET_DIR,
    'train': 'images/train',
    'val': 'images/val',
    'test': 'images/test',
    'nc': 1,  # Number of classes (just "Lesions" class)
    'names': ['Lesions']  # Class name
}

config_path = f'{BASE_DIR}/dataset.yaml'
with open(config_path, 'w') as f:
    yaml.dump(dataset_config, f, default_flow_style=False)

print("\n✅ Dataset configuration created!")
print(f"Config saved to: {config_path}")

# ============================================================
# STEP 5: Verify Dataset
# ============================================================

def verify_dataset():
    """Check if dataset is properly structured"""
    for split in ['train', 'val', 'test']:
        img_count = len(list(Path(f'{IMAGES_DIR}/{split}').glob('*.jpg'))) + \
                    len(list(Path(f'{IMAGES_DIR}/{split}').glob('*.png')))
        lbl_count = len(list(Path(f'{LABELS_DIR}/{split}').glob('*.txt')))
        print(f"{split.upper()}: {img_count} images, {lbl_count} labels")

        if img_count == 0:
            print(f"⚠️  Warning: No images found in {split} set!")
        if lbl_count == 0:
            print(f"⚠️  Warning: No labels found in {split} set!")

print("\n📊 Dataset Summary:")
print("=" * 50)
verify_dataset()
print("=" * 50)

# ============================================================
# STEP 6: Initialize YOLOv8 Model
# ============================================================

print("\n🤖 Initializing YOLOv8 model...")

# Choose model size: yolov8n (nano), yolov8s (small), yolov8m (medium)
# Smaller = faster training, lower accuracy
# Larger = slower training, higher accuracy
model = YOLO('yolov8n.pt')  # Using nano for faster training

print("✅ Model initialized!")

# ============================================================
# STEP 7: Train the Model
# ============================================================

print("\n🚀 Starting training...")
print("=" * 50)

# Training parameters
results = model.train(
    data=config_path,
    epochs=50,              # Number of training epochs
    imgsz=640,              # Image size
    batch=16,               # Batch size (reduce if out of memory)
    patience=10,            # Early stopping patience
    save=True,              # Save checkpoints
    device='cpu',               # Use GPU (0) or CPU ('cpu')
    project=f'{BASE_DIR}/runs',
    name='fish_lesion_detection',
    exist_ok=True,
    pretrained=True,
    optimizer='AdamW',
    verbose=True,
    seed=42,
    deterministic=True,
    single_cls=False,
    rect=False,
    cos_lr=True,
    close_mosaic=10,
    resume=False,
    amp=True,               # Automatic Mixed Precision
    fraction=1.0,
    profile=False,
    freeze=None,
    lr0=0.01,               # Initial learning rate
    lrf=0.01,               # Final learning rate
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=3.0,
    warmup_momentum=0.8,
    warmup_bias_lr=0.1,
    box=7.5,                # Box loss gain
    cls=0.5,                # Classification loss gain
    dfl=1.5,                # DFL loss gain
    pose=12.0,
    kobj=1.0,
    label_smoothing=0.0,
    nbs=64,
    hsv_h=0.015,            # HSV hue augmentation
    hsv_s=0.7,              # HSV saturation augmentation
    hsv_v=0.4,              # HSV value augmentation
    degrees=0.0,            # Rotation augmentation
    translate=0.1,          # Translation augmentation
    scale=0.5,              # Scale augmentation
    shear=0.0,              # Shear augmentation
    perspective=0.0,        # Perspective augmentation
    flipud=0.0,             # Vertical flip probability
    fliplr=0.5,             # Horizontal flip probability
    mosaic=1.0,             # Mosaic augmentation probability
    mixup=0.0,              # Mixup augmentation probability
    copy_paste=0.0          # Copy-paste augmentation probability
)

print("\n✅ Training complete!")

# ============================================================
# STEP 8: Evaluate the Model
# ============================================================

print("\n📈 Evaluating model performance...")
print("=" * 50)

# Validate the model
metrics = model.val()

print(f"\n📊 Validation Results:")
print(f"  mAP50: {metrics.box.map50:.4f}")
print(f"  mAP50-95: {metrics.box.map:.4f}")
print(f"  Precision: {metrics.box.mp:.4f}")
print(f"  Recall: {metrics.box.mr:.4f}")

# Display training results
results_dir = f'{BASE_DIR}/runs/fish_lesion_detection'
print(f"\n📁 Results saved to: {results_dir}")

# Show training curves
if os.path.exists(f'{results_dir}/results.png'):
    display(Image(f'{results_dir}/results.png'))

# ============================================================
# STEP 9: Test Inference
# ============================================================

print("\n🔍 Running test predictions...")

# Load the best trained model
best_model = YOLO(f'{results_dir}/weights/best.pt')

# Run inference on test set
test_results = best_model.predict(
    source=f'{IMAGES_DIR}/test',
    save=True,
    save_txt=True,
    save_conf=True,
    project=f'{BASE_DIR}/predictions',
    name='test_predictions',
    exist_ok=True,
    conf=0.25,  # Confidence threshold
    iou=0.45    # IoU threshold for NMS
)


# Graphs

print("\n📊 Calculating detailed metrics...")

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

def calculate_f_star(f1):
    """Calculate F* score from F1 score using formula: F* = F / (2 - F)"""
    return f1 / (2 - f1)

y_true = []
y_pred = []

for label_file in Path(f'{LABELS_DIR}/test').glob('*.txt'):
    with open(label_file, 'r') as f:
        lines = f.readlines()
        has_lesions = len(lines) > 0
        y_true.append(1 if has_lesions else 0)

pred_dir = f'{BASE_DIR}/predictions/test_predictions/labels'
for img_file in sorted(Path(f'{IMAGES_DIR}/test').glob('*.jpg')) + sorted(Path(f'{IMAGES_DIR}/test').glob('*.png')):
    pred_file = Path(pred_dir) / (img_file.stem + '.txt')
    if pred_file.exists():
        with open(pred_file, 'r') as f:
            lines = f.readlines()
            has_lesions = len(lines) > 0

# Learning curve
# ============================================================

print("\n" + "="*60)
print("YOLO LEARNING CURVE - COMPARING DATA SIZES")
print("="*60)

import shutil
from pathlib import Path

data_percentages = [0.5, 0.75, 1.0]
yolo_learning_results = []

original_train_images = f'{downloaded_dataset_path}/train/images'
original_train_labels = f'{downloaded_dataset_path}/train/labels'
original_valid_images = f'{downloaded_dataset_path}/valid/images'
original_valid_labels = f'{downloaded_dataset_path}/valid/labels'

train_images = list(Path(original_train_images).glob('*.jpg')) + list(Path(original_train_images).glob('*.png'))
train_labels = list(Path(original_train_labels).glob('*.txt'))


for pct in data_percentages:
    print(f"\n{'='*60}")
    print(f"Training YOLO with {int(pct*100)}% of data")
    print(f"{'='*60}")

    subset_dir = f'{BASE_DIR}/dataset_{int(pct*100)}'
    subset_images_train = f'{subset_dir}/images/train'
    subset_labels_train = f'{subset_dir}/labels/train'
    subset_images_val = f'{subset_dir}/images/val'
    subset_labels_val = f'{subset_dir}/labels/val'

    os.makedirs(subset_images_train, exist_ok=True)
    os.makedirs(subset_labels_train, exist_ok=True)
    os.makedirs(subset_images_val, exist_ok=True)
    os.makedirs(subset_labels_val, exist_ok=True)

    n_samples = int(len(train_images) * pct)

    if pct < 1.0:
        sampled_images = np.random.choice(train_images, n_samples, replace=False)
    else:
        sampled_images = train_images

    print(f"Copying {n_samples} training images and labels...")

    for img_path in sampled_images:
        img_name = img_path.name
        label_name = img_path.stem + '.txt'

        shutil.copy(img_path, f'{subset_images_train}/{img_name}')

        label_path = Path(original_train_labels) / label_name
        if label_path.exists():
            shutil.copy(label_path, f'{subset_labels_train}/{label_name}')

    print("Copying validation files...")
    for img_path in Path(original_valid_images).glob('*'):
        shutil.copy(img_path, f'{subset_images_val}/{img_path.name}')
    for lbl_path in Path(original_valid_labels).glob('*.txt'):
        shutil.copy(lbl_path, f'{subset_labels_val}/{lbl_path.name}')

    subset_config = {
        'path': subset_dir,
        'train': 'images/train',
        'val': 'images/val',
        'nc': 1,
        'names': ['Lesions']
    }

    subset_config_path = f'{subset_dir}/data.yaml'
    with open(subset_config_path, 'w') as f:
        yaml.dump(subset_config, f, default_flow_style=False)

    print(f"\n Dataset subset created at: {subset_dir}")
    print(f"Training images: {len(list(Path(subset_images_train).glob('*')))}")
    print(f"Training labels: {len(list(Path(subset_labels_train).glob('*.txt')))}")

    print(f"\nTraining YOLO with {int(pct*100)}% data...")
    model_subset = YOLO('yolov8n.pt')

    results_subset = model_subset.train(
        data=subset_config_path,
        epochs=30,
        imgsz=640,
        batch=16,
        patience=8,
        save=True,
        device='cpu',
        project=f'{BASE_DIR}/runs',
        name=f'yolo_{int(pct*100)}pct',
        exist_ok=True,
        verbose=False
    )

    print(f"\nEvaluating YOLO {int(pct*100)}% model...")
    metrics_subset = model_subset.val()

    test_images_path = f'{IMAGES_DIR}/test'
    test_labels_path = f'{LABELS_DIR}/test'

    y_true_yolo = []
    y_pred_yolo = []

    for img_file in Path(test_images_path).glob('*.jpg'):
        label_file = Path(test_labels_path) / (img_file.stem + '.txt')
        if label_file.exists():
            with open(label_file, 'r') as f:
                has_lesions_true = len(f.readlines()) > 0
        else:
            has_lesions_true = False
        y_true_yolo.append(1 if has_lesions_true else 0)

        pred_results = model_subset.predict(source=str(img_file), conf=0.25, verbose=False)
        has_lesions_pred = len(pred_results[0].boxes) > 0
        y_pred_yolo.append(1 if has_lesions_pred else 0)

    accuracy = accuracy_score(y_true_yolo, y_pred_yolo)
    precision = precision_score(y_true_yolo, y_pred_yolo, zero_division=0)
    recall = recall_score(y_true_yolo, y_pred_yolo, zero_division=0)
    f1 = f1_score(y_true_yolo, y_pred_yolo, zero_division=0)
    f_star = calculate_f_star(f1)

    # Store results
    yolo_learning_results.append({
        'data_percentage': int(pct * 100),
        'training_samples': n_samples,
        'mAP50': float(metrics_subset.box.map50),
        'mAP50_95': float(metrics_subset.box.map),
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1,
        'f_star': f_star
    })


    print(f"\nResults for {int(pct*100)}% data:")
    print(f"  Detection mAP50: {metrics_subset.box.map50:.4f}")
    print(f"  Classification Accuracy: {accuracy:.4f}")
    print(f"  Classification F1: {f1:.4f}")
    print(f"  Classification F*: {f_star:.4f}")

yolo_learning_df = pd.DataFrame(yolo_learning_results)

# Learning curve
# ============================================================

print("\n" + "="*60)
print("PLOTTING YOLO LEARNING CURVE")
print("="*60)

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('YOLO Learning Curve: Performance vs Training Data Size',
             fontsize=16, fontweight='bold', y=1.02)

metrics = ['accuracy', 'precision', 'recall', 'f1', 'f_star']
titles = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'F* Score']
colors = ['#3498db', '#e74c3c', '#2ecc71', '#f39c12', '#9b59b6']

for idx, (metric, title, color) in enumerate(zip(metrics, titles, colors)):
    row = idx // 3
    col = idx % 3
    ax = axes[row, col]

    ax.plot(yolo_learning_df['data_percentage'],
            yolo_learning_df[metric],
            '^-',
            color=color,
            linewidth=3,
            markersize=12,
            label=title)

    for i, row_data in yolo_learning_df.iterrows():
        ax.text(row_data['data_percentage'],
                row_data[metric] + 0.02,
                f"{row_data[metric]:.3f}",
                ha='center',
                va='bottom',
                fontsize=10,
                fontweight='bold')

    ax.set_xlabel('Training Data Size (%)', fontsize=12, fontweight='bold')
    ax.set_ylabel(title, fontsize=12, fontweight='bold')
    ax.set_title(f'{title} vs Data Size', fontsize=13, fontweight='bold')
    ax.grid(True, alpha=0.3, linestyle='--')
    ax.set_ylim([0, 1.1])
    ax.set_xticks(yolo_learning_df['data_percentage'])

ax = axes[1, 2]
ax.axis('off')

summary_text = "Summary Table\n" + "="*50 + "\n\n"
summary_text += f"{'Data %':<10} {'Samples':<10} {'mAP50':<8} {'Acc':<8} {'F1':<8}\n"
summary_text += "-"*50 + "\n"
for _, row in yolo_learning_df.iterrows():
    summary_text += f"{row['data_percentage']:<10} {row['training_samples']:<10} {row['mAP50']:<8.3f} {row['accuracy']:<8.3f} {row['f1']:<8.3f}\n"

acc_50_to_75 = ((yolo_learning_df.iloc[1]['accuracy'] - yolo_learning_df.iloc[0]['accuracy']) /
                yolo_learning_df.iloc[0]['accuracy'] * 100)
acc_75_to_100 = ((yolo_learning_df.iloc[2]['accuracy'] - yolo_learning_df.iloc[1]['accuracy']) /
                 yolo_learning_df.iloc[1]['accuracy'] * 100)

summary_text += "\n" + "="*50 + "\n"
summary_text += "Improvement Rates:\n"
summary_text += f"50% → 75%:  {acc_50_to_75:+.1f}%\n"
summary_text += f"75% → 100%: {acc_75_to_100:+.1f}%\n"

ax.text(0.1, 0.5, summary_text,
        fontsize=10,
        family='monospace',
        verticalalignment='center')

plt.tight_layout()
plt.savefig('yolo_learning_curve.png', dpi=300, bbox_inches='tight')
plt.show()

print("\n" + "="*60)
print("YOLO PERFORMANCE COMPARISON")
print("="*60)
print(yolo_learning_df.to_string(index=False))
print("="*60)